In [1]:
import numpy as np

In [31]:
arr = np.array([1, 2, 3])
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(matrix)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [2]:
zeros_arr = np.zeros((2, 3)) 
ones_arr = np.ones((3, 4))

In [3]:
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
arrange = np.arange(0,22,3) #(start, stop, step)
print(arrange)

[ 0  3  6  9 12 15 18 21]


In [24]:
arr1 = np.linspace(0, 5, 10)
print(arr1)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [26]:
random_arr = np.random.rand(3,3)
print(random_arr)

[[0.21980116 0.98571753 0.09398839]
 [0.69595234 0.35013415 0.96509624]
 [0.38191697 0.43294151 0.49333911]]


In [40]:
arr = np.array([1,2,3,4,5])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

15
3.0
5
1


In [45]:
arr1 = np.array([1,5,2,6,4,0])
max_idx = arr1.argmax() # the index of the max value
print(max_idx)
min_idx = arr1.argmin() # the index of the min value
print(min_idx)

3
5
